version: '3.8'

services:
  infiniteplexlibrary:
    image: arjanterheegde/infiniteplexlibrary:latest
    container_name: infiniteplexlibrary
    user: "99:100"
    ports:
      - "3000:3000"
    volumes:
      - /mnt/user/realdebrid/data:/mount #Should be the same as Plex
      - /mnt/user/data/plex:/media # Radarr movie path
      - /mnt/user/data/plex:/plex # Plex movie path (could be the same as above)
      - /mnt/user/appdata/infiniteplexlibrary:/infiniteplexlibrary # Dummy folder
    environment:
      PUID: 99
      PGID: 100
      UMASK: 002
      TZ: Europe/Amsterdam  
    env_file:
      - .env 
    restart: unless-stopped

  dailymaintenance:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - /mnt/user/realdebrid/data:/mount #Should be the same as Plex
      - /mnt/user/data/plex:/media # Radarr movie path
      - /mnt/user/data/plex:/plex # Plex movie path (could be the same as above)
      - /mnt/user/appdata/infiniteplexlibrary:/infiniteplexlibrary # Dummy folder
    entrypoint: ["sh", "-c", "node scripts/dailyMovieMaintenance.js"]
    environment:
      - .env 
    restart: "no"    