version: '3.8'

services:
  infiniteplexlibrary:
    build:
      context: .
      dockerfile: Dockerfile
    image: arjanterheegde/infiniteplexlibrarry:latest
    pull_policy: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
